/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stackoverflow;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Wajahat
 */
public class signIn extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public signIn() {
        initComponents();
//        signInButton.setOpaque(false);
//        backButton.setOpaque(false);
//        emailTextField.setOpaque(false);
//        PasswordField.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        stackOverFlowLogoLabel = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();
        doNotHaveAnAccountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In");
        setResizable(false);
        getContentPane().setLayout(null);

        signUpButton.setBackground(new java.awt.Color(0, 255, 0));
        signUpButton.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        signUpButton.setText("Register");
        signUpButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 1, true));
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButton);
        signUpButton.setBounds(690, 520, 90, 30);

        emailLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        emailLabel.setText("Email :");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(430, 270, 180, 60);

        passwordLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        passwordLabel.setText("Password :");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(430, 350, 300, 70);

        emailTextField.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        emailTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField);
        emailTextField.setBounds(680, 280, 270, 50);

        backButton.setBackground(new java.awt.Color(0, 0, 204));
        backButton.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(1110, 20, 180, 50);

        PasswordField.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        PasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        getContentPane().add(PasswordField);
        PasswordField.setBounds(680, 360, 270, 50);

        stackOverFlowLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stackoverflow/stackoverflow-logo-700x467.png"))); // NOI18N
        getContentPane().add(stackOverFlowLogoLabel);
        stackOverFlowLogoLabel.setBounds(370, -10, 650, 310);

        signInButton.setBackground(new java.awt.Color(0, 0, 204));
        signInButton.setFont(new java.awt.Font("Century Schoolbook", 0, 36)); // NOI18N
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setText("Sign In");
        signInButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signInButton);
        signInButton.setBounds(430, 440, 520, 60);

        doNotHaveAnAccountLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        doNotHaveAnAccountLabel.setText("Don't Have An Account?");
        getContentPane().add(doNotHaveAnAccountLabel);
        doNotHaveAnAccountLabel.setBounds(430, 520, 270, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:

        Signup obj = new Signup();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        obj.setSize(screenSize.width, screenSize.height);
        obj.setVisible(true);
        obj.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_signUpButtonActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel doNotHaveAnAccountLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel stackOverFlowLogoLabel;
    // End of variables declaration//GEN-END:variables
}
