/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stackoverflow;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Wajahat
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
//        signUpButton.setOpaque(false);
//        backButton.setOpaque(false);
//        PasswordTextField.setOpaque(false);
//        confirmPasswordTextField.setOpaque(false);
//        emailTextField.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        emaillLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        confirmPasswordTextField = new javax.swing.JPasswordField();
        stackOverFlowLogoLabel = new javax.swing.JLabel();
        doNotHaveAnAccountLabel = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setResizable(false);
        getContentPane().setLayout(null);

        passwordLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        passwordLabel.setText("Password :");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(350, 320, 300, 60);

        confirmPasswordLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        confirmPasswordLabel.setText("Confirm Password :");
        getContentPane().add(confirmPasswordLabel);
        confirmPasswordLabel.setBounds(350, 390, 520, 70);

        signUpButton.setBackground(new java.awt.Color(0, 0, 204));
        signUpButton.setFont(new java.awt.Font("Century Schoolbook", 0, 36)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(255, 255, 255));
        signUpButton.setText("Sign Up");
        signUpButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        getContentPane().add(signUpButton);
        signUpButton.setBounds(350, 470, 690, 60);

        backButton.setBackground(new java.awt.Color(0, 0, 204));
        backButton.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(1140, 20, 160, 50);

        emaillLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        emaillLabel.setText("Email :");
        getContentPane().add(emaillLabel);
        emaillLabel.setBounds(350, 250, 180, 60);

        emailTextField.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        emailTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField);
        emailTextField.setBounds(740, 240, 300, 50);

        PasswordTextField.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        PasswordTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        getContentPane().add(PasswordTextField);
        PasswordTextField.setBounds(740, 320, 300, 50);

        confirmPasswordTextField.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        confirmPasswordTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        getContentPane().add(confirmPasswordTextField);
        confirmPasswordTextField.setBounds(740, 400, 300, 50);

        stackOverFlowLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stackoverflow/stackoverflow-logo-700x467.png"))); // NOI18N
        getContentPane().add(stackOverFlowLogoLabel);
        stackOverFlowLogoLabel.setBounds(330, -40, 680, 320);

        doNotHaveAnAccountLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        doNotHaveAnAccountLabel.setText("Already Have An Account?");
        getContentPane().add(doNotHaveAnAccountLabel);
        doNotHaveAnAccountLabel.setBounds(350, 550, 280, 30);

        signInButton.setBackground(new java.awt.Color(0, 255, 0));
        signInButton.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        signInButton.setText("Sign In");
        signInButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 1, true));
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signInButton);
        signInButton.setBounds(640, 550, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        signIn obj = new signIn();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        obj.setSize(screenSize.width, screenSize.height);
        obj.setVisible(true);
        obj.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_signInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JPasswordField confirmPasswordTextField;
    private javax.swing.JLabel doNotHaveAnAccountLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel emaillLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel stackOverFlowLogoLabel;
    // End of variables declaration//GEN-END:variables
}
